### ISSUE TITLE
Automate user contributions to README as stated in CONTRIBUTING.md

### ISSUE THREAD

**Issue by bigolboyyo** [climate-tech-handbook/data-magic#27]
![image](https://github.com/climate-tech-handbook/data-magic/assets/95878821/6d4006aa-8d02-45b1-a4d2-9e89d8f6e8b0)

We want to make sure everyone gets credit for their contributions. Any ideas to automate this process?

**Comment by yavuzibr** [comment]
I created a mini program (mainly created using Chat-GPT-4) for automating the contributors. I'll fork and add the file you can try and if it is okay for you, you can adjust and use it

**Comment by futuresoup** [comment]
Thanks @yavuzibr! Nice to meet you 👋

Care to [join us on Slack](https://chat.climatetechhandbook.com)?

I'd love to learn about your interests and motivations for contributing to The Climate Tech Handbook

**Comment by yavuzibr** [comment]
Thanks for your invitation. There is no particular reason. I am a junior artificial intelligence engineer who wants to contribute to open-source projects and improve himself. I wanted to help because I like the idea of automating contributors, but due to other projects and online courses, I didn't have much time so I created a quick code block with help from ChatGPT. I wish you good work
